openapi: 3.0.3
info:
  title: ViaggiaTreno
  description: |-
    Reverse engineered ViaggiaTreno APIs - real time information on Trenitalia's trains.

    Research done by [sabas](https://github.com/sabas/trenitalia).
  version: 0.1.0
externalDocs:
  description: ViaggiaTreno
  url: http://www.viaggiatreno.it/infomobilita/index.jsp
servers:
  - url: http://www.viaggiatreno.it/infomobilita/resteasy/viaggiatreno
tags:
  - name: stations
    description: Stations' data
paths:
  /autocompletaStazione/{input}:
    get:
      tags:
        - stations
      summary: Get possible autocompletions
      description: Get possible autocompletions for a possible query
      parameters:
        - name: input
          in: path
          description: Query
          required: true
          schema:
            type: string
      responses:
        "200":
          description: successful operation
          content:
            text/plain:
              schema:
                type: string
  /autocompletaStazioneNTS/{input}:
    get:
      tags:
        - stations
      summary: Get possible autocompletions
      description: Get possible autocompletions for a possible query
      parameters:
        - name: input
          in: path
          description: Query
          required: true
          schema:
            type: string
      responses:
        "200":
          description: successful operation
          content:
            text/plain:
              schema:
                type: string
  /cercaStazione/{input}:
    get:
      tags:
        - stations
      summary: Get possible autocompletions
      description: Get possible autocompletions for a possible query
      parameters:
        - name: input
          in: path
          description: Query
          required: true
          schema:
            type: string
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Localita'
  /elencoStazioni/{idRegione}:
    get:
      tags:
        - stations
      summary: Get possible autocompletions
      description: Get possible autocompletions for a possible query
      parameters:
        - name: idRegione
          in: path
          description: Query
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/StationDetails'
components:
  schemas:
    Localita:
      type: object
      properties:
        nomeLungo:
          type: string
        nomeBreve:
          type: string
        label:
          type: string
          nullable: true
        id:
          type: string
      required:
        - nomeLungo
        - nomeBreve
        - label
        - id
    StationDetails:
      description: Details of a station when listing
      type: object
      properties:
        codReg:
          type: integer
        tipoStazione:
          type: integer
        localita:
          $ref: "#/components/schemas/Localita"
      required:
        - codReg
        - tipoStazione
        - localita
