openapi: 3.0.3
info:
  title: ViaggiaTreno
  description: |-
    Reverse engineered ViaggiaTreno APIs - real time information on Trenitalia's trains.
    Research done by [sabas](https://github.com/sabas/trenitalia).
  version: 0.1.0
externalDocs:
  description: ViaggiaTreno
  url: http://www.viaggiatreno.it/infomobilita/index.jsp
servers:
  - url: http://www.viaggiatreno.it/infomobilita/resteasy/viaggiatreno
tags:
  - name: stations
    description: Stations' data
paths:
  /autocompletaStazione/{input}:
    get:
      tags:
        - stations
      summary: Get possible autocompletions
      description: Get possible autocompletions for a given query
      parameters:
        - name: input
          in: path
          description: Query
          required: true
          schema:
            type: string
      responses:
        "200":
          description: successful operation
          content:
            text/plain:
              schema:
                type: string
  /autocompletaStazioneNTS/{input}:
    get:
      tags:
        - stations
      summary: Get possible autocompletions
      description: Get possible autocompletions for a given query
      parameters:
        - name: input
          in: path
          description: Query
          required: true
          schema:
            type: string
      responses:
        "200":
          description: successful operation
          content:
            text/plain:
              schema:
                type: string
  /cercaStazione/{input}:
    get:
      tags:
        - stations
      summary: Get possible stations
      description: Get possible stations for a given query
      parameters:
        - name: input
          in: path
          description: Query
          required: true
          schema:
            type: string
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Localita"
  /elencoStazioni/{idRegione}:
    get:
      tags:
        - stations
      summary: Get all stations in a region
      parameters:
        - name: idRegione
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/StationDetails"
  /regione/{idStazione}:
    get:
      tags:
        - stations
      summary: Get the idRegione for an idStazione
      parameters:
        - name: idStazione
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: integer
  /dettaglioStazione/{idStazione}/{idRegione}:
    get:
      tags:
        - stations
      summary: Get station details
      parameters:
        - name: idStazione
          in: path
          required: true
          schema:
            type: string
        - name: idRegione
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StationDetails"
components:
  schemas:
    Localita:
      type: object
      properties:
        nomeLungo:
          type: string
        nomeBreve:
          type: string
        label:
          type: string
          nullable: true
        id:
          type: string
      required:
        - nomeLungo
        - nomeBreve
        - label
        - id
    StationDetails:
      description: Details of a station when listing
      type: object
      properties:
        codReg:
          type: integer
        tipoStazione:
          type: integer
        localita:
          $ref: "#/components/schemas/Localita"
        codiceStazione:
          type: string
        codStazione:
          type: string
        lat:
          type: number
        lon:
          type: number
        esterno:
          type: boolean
        nomeCitta:
          type: string
      required:
        - codReg
        - tipoStazione
        - localita
        - codiceStazione
        - codStazione
        - lat
        - lon
        - esterno
        - nomeCitta
